// src/types/Order.ts

/**
 * Defines the structure of an item within an order.
 * This is what the user purchased.
 */
export interface OrderItem {
    // This ID is generated by the database for the OrderItem record
    id: number;
    
    // ID of the sweet purchased
    sweet_id: number;
    
    // The price of the sweet at the time of purchase (important for historical accuracy)
    price_at_purchase: number;
    
    // The quantity purchased by the user
    quantity: number;
    
    // The name of the sweet (often included in the backend response for convenience)
    sweet_name?: string; 
}

/**
 * Defines the structure of a complete order record.
 */
export interface Order {
    // Unique ID for the order
    id: number;
    
    // ID of the user who placed the order
    user_id: number; 
    
    // Total calculated cost of all items in the order
    total_price: number; 
    
    // Status of the order (e.g., 'Pending', 'Completed', 'Shipped')
    status: string; 
    
    // Timestamp of when the order was created
    created_at: string; 
    
    // Array of all items included in this order
    items: OrderItem[];
}